---
#- name: Install proxmox ve
#  hosts: localhost
#  roles:
#    - { role: install-proxmox, tags: ["install-pve"]}

- name: Clone VM
  hosts: bidmachine
  roles:
    - { role: proxmox-clone, tags: ["clone"]}
