---
#- name: Install proxmox ve
#  hosts: localhost
#  roles:
#    - { role: install-proxmox, tags: ["install-pve"]}

- name: Clone VM
  hosts: bidmachine
  roles:
    - { role: proxmox-clone, tags: ["clone"]}

- name: Install docker
  hosts: vms
  become: true
  roles:
    - { role: docker-install, tags: ["docker"]}

- name: Deploy MySQL
  hosts: db_server
  become: true
  roles:
    - {role: deploy-mysql, tags: ["mysql"]}

- name: Deploy Wordpress
  hosts: web_server
  become: true
  roles:
    - {role: deploy-wordpress, tags: ["wp"]}
