---
#- name: Install proxmox ve
#  hosts: localhost
#  roles:
#    - { role: install-proxmox, tags: ["install-pve"]}

- name: Set firewall rules
  hosts: bidmachine
  roles:
    - {role: firewall, tags: ["firewall"]}

- name: Clone VM
  hosts: bidmachine
  roles:
    - { role: proxmox-clone, tags: ["clone"]}

- name: Install docker
  hosts: vms
  become: true
  roles:
    - { role: docker-install, tags: ["docker"]}

- name: Deploy MySQL
  hosts: db_server
  become: true
  roles:
    - {role: deploy-mysql, tags: ["mysql"]}

- name: Deploy Wordpress
  hosts: web_server
  become: true
  roles:
    - {role: deploy-wordpress, tags: ["wp"]}

- name: Save rules
  ansible.builtin.command:
    cmd: iptables-save > /etc/iptables.up.rules

- name: Started rules on a reboot
  ansible.builtin.file:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
