- name: Deploy Wordpress
  docker_container:
    image: wordpress
    name: wordpress
    state: started
    restart_policy: on-failure
    published_ports: [ "80:80" ]
    env:
      WORDPRESS_DB_HOST: 192.168.1.5
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "12345"
      WORDPRESS_DB_NAME: wp_db
