---
- name: Add IP address
  lineinfile:
    path: /etc/hosts
    search_string: '127.0.1.1'
    line: "{{ ansible_agge.ipv4.address }}\t{{ ansible_hostname }}\t{{ ansible_hostname }}"

- name: Add Proxmox VE repository key
  ansible.builtin.apt_key:
    url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    state: present

- name: Add Proxmox VE repository
  apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
    update_cache: yes
    upgrade: full

- name: Install Proxmox packages
  apt:
    name:
      - proxmox-ve 
      #- postfix 
      - open-iscsi
      - python3-pip
      
- name: Install proxmove python package
  pip:
    name: proxmove

- name: Config network
  ansible.builtin.copy:
    src: interfaces.new
    dest: /etc/network/interfaces.new

- name: Reboot system
  reboot:
