---
- name: Download the image
  ansible.builtin.get_url:
    url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
    dest: /root/focal-cloudimg.img

- name: Create VM
  community.general.proxmox_kvm:
    node: "{{ pve_node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_pass }}"
    api_host: "{{ api_host }}"
    name: wp-dbserver
    vmid: 102
    memory: 2048
    cores: 2
    net:
      net0: 'virtio,bridge=vmbr0'
    ide:
      ide2: 'local:cloudinit,format=qcow2'
    ciuser: "{{ server_user }}"
    cipassword: "{{server_pass}}"
    sshkeys: "{{ pub_ssh }}"
    nameservers: 8.8.8.8
    ipconfig:
      ipconfig0: 'ip=192.168.1.5/24,gw=192.168.1.1'

- name: Import disk to storage
  ansible.builtin.command:
    cmd: "qm importdisk 102 /root/focal-cloudimg.img local"

- name: Attach new disk to the VM
  ansible.builtin.command:
    cmd: "qm set 102 --scsihw virtio-scsi-pci --scsi0 local:102/vm-102-disk-0.raw"

- name: Set boot disk
  ansible.builtin.command:
    cmd: "qm set 102 --boot c --bootdisk scsi0"

- name: Resize disk
  ansible.builtin.command:
    cmd: "qm resize 102 scsi0 10G"

- name: Start VM
  community.general.proxmox_kvm:
    node: "{{ pve_node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_pass }}"
    api_host: "{{ api_host }}"
    name: wp-dbserver
    state: started
