---
- name: Create new VM using Cloud-Init
  community.general.proxmox_kvm:
    node: "{{ pve_node }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_pass }}"
    api_host: "{{ api_host }}"
    clone: "{{ clone_name }}"
    name: "{{ item.value.name }}"
    newid: "{{ item.value.newid }}"
    net:
      net0: 'virtio,bridge=vmbr'
    ipconfig:
      ipconfig0: '{{ item.value.ip_addr }}/24,gw=192.168.1.1'
    
  loop: "{{ lookup('dict', vms) }}"