---
- name: Forward port 80
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: agge
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Prerouting 80 port
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: agge
    protocol: tcp
    destination_port: 80
    jump: DNAT
    to_destination: 192.168.1.6

- name: Forward port 22
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: agge
    protocol: tcp
    destination_port: 22
    jump: ACCEPT

- name: Prerouting 2222 port
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: agge
    protocol: tcp
    destination_port: 2222
    jump: DNAT
    to_destination: 192.168.1.5:22

- name: Prerouting 2223 port
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: agge
    protocol: tcp
    destination_port: 2223
    jump: DNAT
    to_destination: 192.168.1.6:22

- name: Save rules
  ansible.builtin.command:
    cmd: iptables-save > /etc/iptables.up.rules

- name: Started rules on a reboot
  ansible.builtin.file:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
